INSERT INTO creatures (name, source, cr, xp, ac, dexmod, artic, coastal, desert, forest, grasslands, hill, mountain, swamp, underdark, underwater,urban )
    VALUES
        ('Aarakocra', 'Monster Manual page 12', '1/4', 50, 12, 2, true, true, true, true, true, true, true, true, false, false, true),
        ('Aboleth', 'Monster Manual page 13', '10', 5900, 17, -1, false, true, false, true, false, false, false, true, true, true ,false),
        ('Deva', 'Monster Manual page 16', '10', 5900, 17, 4, true, true, true, true, true, true, true, true, true, false, true),
        ('Planetar', 'Monster Manual page 17', '16', 15000, 19, 5, true, true, true, true, true, true, true, true, false, false, true),
        ('Solar', 'Monster Manual page 18', '21', 33000, 21, 6, true, true, true, true, true, true, true, true, false, false, true),
        ('Animated Armor', 'Monster Manual page 19', '1', 200, 18, 0, true, true, true, true, true, true, true, true, false, false, true),
        ('Flying Sword', 'Monster Manual page 20', '1/4', 50, 17, 2, false, false, false, false, false, false, false, false, false, false, true),
        ('Rug of Smothering', 'Monster Manual page 20', '2', 450, 12, 2, false, false, false, false, false, false, false, false, false, false, true),
        ('Ankheg', 'Monster Manual page 21', '2', 450, 14, 0, false, true, false, true, true, true, false, false, true, false, false),
        ('Azer', 'Monster Manual page 22', '2', 450, 17, 1, false, false, false, false, false, false, true, false, false, false, false),
        ('Banshee', 'Monster Manual page 23', '4', 1100, 12, 2, true, true, true, true, true, true, true, true, false, true, true ),
        ('Basilisk', 'Monster Manual page 24', '3', 700, 15, -1, false, true, true, true, true, true, true, true, false, false, true),
        ('Behir', 'Monser Manual page 25', '11', 7200, 17, 3, false, true, true, true, false, true, false, false, false, false, false),
        ('Beholder', 'Monster Manual page 28', '13', 10000, 18, 2, false, false, false, false, false, false, false, false, true, false, true),
        ('Death Tyrant', 'Monster Manual page 29', '14', 11500, 19, 2, false, false, false, false, false, false, false, false, true, false, true),
        ('Spectator', 'Monster Manual page 30', '3', 700, 14, 2, false, false, false, false, false, false, false, false, true, false, true),
        ('Needle Blight', 'Monster Manual page 32', '1/4', 50, 12, 1, false, false, false, true, true, true, true, true, false, false, false),
        ('Twig Blight', 'Monster Manual page 32', '1/8', 25, 13, 1, false, false, false, true, true, true, true, false, false, false, false),
        ('Vine Blight', 'Monster Manual page 32', '1/2', 100, 12, -1, false, false, false, true, true, true, true, false, false, false, false),
        ('Bugbear', 'Monster Manual page 33', '1', 200, 16, 2, false, true, true, true, true, true, true, true, false, false, false),
        ('Bugbear Chief', 'Monster Manual page 33', '3', 700, 17, 2, false, true, true, true, true, true, true, true, false, false, false),
        ('Bulette', 'Monster Manual page 34', '5', 1800, 17, 0, false, true, false, true, true, true, true, true, false, false, false),
        ('Bullywug', 'Monster Manual page 35', '1/4', 50, 15, 1, false, true, false, true, false, false, false, true, false, false, false),
        ('Cambion', 'Monster Manual page 36', '5', 1800, 19, 4, false, true, true, true, true, true, true, true, false, false, true),
        ('Carrion Crawler', 'Monster Manual page 37', '2', 450, 13, 1, false, true, true, true, true, true, true, true, true, false, true),
        ('Centaur', 'Monster Manual page 38', '2', 450, 12, 2, false, true, false, true, true, true, true, true, false, false, false),
        ('Chimera', 'Monster Manual page 39', '6', 2300, 14, 0, false, true, false, true, true, true, true, false, false, false, false),
        ('Chuul', 'Monster Manual page 40', '4', 1100, 16, 0, false, true, false, false, false, false, false, true, false, true, false),
        ('Cloaker', 'Monster Manual page 41', '8', 3900, 14, 2, false, false, false, false, false, false, false, false, true, false, false),
        ('Cockatrice', 'Monster Manual page 42', '1/2', 100, 11, 1, false, false, true, false, true, true, true, true, false, false, false),
        ('Coaul', 'Monster Manual page 43', '4', 1100, 19, 5, false, false, false, false, false, false, false, false, true, false, false),
        ('Crawling Claw', 'Monster Manual page 44', '0', 10, 12, 2, true, false, true, true, true, false, false, true, true, false, true),
        ('Cyclops', 'Monster Manual page 45', '6', 2300, 14, 0, false, true, true, true, true, true, true, true, false, false, false),
        ('Darkmantel', 'Monster Manual page 46', '1/2', 100, 11, 1, false, false, false, false, false, false, false, false, true, false, false),
        ('Death Knight', 'Monster Manual page 47', '17', 18000, 20, 0, true, true, true, true, true, true, true, true, false, false, true),
        ('Demilich', 'Monster Manual page 48', '18', 20000, 20, 5, false, false, false, false, false, false, false, false, false, false, true),
        ('Balor', 'Monster Manual page 54', '19', 22000, 19, 2, false, false, false, false, false, false, false, false, false, false, false),
        ('Barlgura', 'Monster Manual page 55', '5', 1800, 15, 2, false, false, false, false, false, false, false, false, false, false, false),
        ('Chasme', 'Monster Manual page 56', '6', 2300, 15, 2, false, false, false, false, false, false, false, false, false, false, false),
        ('Dretch', 'Monster Manual page 57', '1/4', 50, 11, 0, false, false, false, false, false, false, false, false, false, false, false),
        ('Glabrezu', 'Monster Manual page 58', '9', 5000, 17, 2, false, false, false, false, false, false, false, false, false, false, false),
        ('Goristro', 'Monster Manual page 59', '17', 18000, 19, 0, false, false, false, false, false, false, false, false, false, false, false),
        ('Herzou', 'Monster Manual page 60', '8', 3900, 16, 3, false, false, false, false, false, false, false, false, false, false, false),
        ('Manes', 'Monster Manual page 60', '1/8', 25, 9, -1, false, false, false, false, false, false, false, false, false, false, false),
        ('Marilith', 'Monster Manual page 61', '16', 15000, 18, 5, false, false, false, false, false, false, false, false, false, false, false),
        ('Nalfeshnee', 'Monster Manual page 62', '13', 10000, 18, 0, false, false, false, false, false, false, false, false, false, false, false),
        ('Quasit', 'Monster Manual page 63', '1', 200, 13, 3, false, false, true, true, false, false, true, true, true, false, true),
        ('Shadow Demon', 'Monster Manual page 64', '4', 1100, 13, 3, false, false, false, false, false, false, false, false, false, false, false),
        ('Vrock', 'Monster Manual page 64', '6', 2300, 15, 2, false, false, false, false, false, false, false, false, false, false, false),
        ('Yochlol', 'Monster Manual page 65', '10', 5900, 15, 2, false, false, false, false, false, false, false, false, false, false, false),
        ('Barded Devil', 'Monster Manual page 70', '5', 1800, 15, 3, false, false, false, false, false, false, false, false, false, false, false),
        ('Bearded Devil', 'Monster Manual page 70', '3', 700, 13, 2, false, false, false, false, false, false, false, false, false, false, false),
        ('Bone Devil', 'Monster Manual page 71', '9', 5000, 19, 3, false, false, false, false, false, false, false, false, false, false, false),
        ('Chain Devil', 'Monster Manaul page 72', '8', 3900, 16, 2, false, false, false, false, false, false, false, false, false, false, false),
        ('Erinyes', 'Monster Manual page 73', '12', 8400, 18, 3, false, false, false, false, false, false, false, false, false, false, false),
        ('Horned Devil', 'Monster Manual page 74', '11', 7200, 18, 3, false, false, false, false, false, false, false, false, false, false, false),
        ('Ice Devil', 'Monster Manual page 75', '14', 11500, 18, 2, false, false, false, false, false, false, false, false, false, false, false),
        ('Imp', 'Monster Manual page 76', '1', 200, 11, 3, false, false, true, true, false, false, true, true, true, false, true),
        ('Lemure', 'Monster Manual page 76', '0', 10, 7, -3, false, false, false, false, false, false, false, false, false, false, false),
        ('Pit Fiend', 'Monster Manual page 77', '20', 25000, 19, 2, false, false, false, false, false, false, false, false, false, false, false),
        ('Spined Devil', 'Monster Manual page 78', '2', 450, 13, 2, false, false, false, false, false, false, false, false, false, false, false),
        ('Allosaurus', 'Monster Manual page 79', '2', 450, 13, 1, false, false, false, false, false, false, false, false, false, false, false),
        ('Ankylosaurus', 'Monster Manual page 79', '3', 700, 15, 0, false, false, false, false, false, false, false, false, false, false, false),
        ('Plesiosaurus', 'Monster Manual page 80', '2', 450, 13, 2, false, false, false, false, false, false, false, false, false, true, false),
        ('Triceratops', 'Monster Manual page 80', '5', 1800, 13, -1, false, false, false, false, false, false, false, false, false, false, false),
        ('Pteranodon', 'Monster Manual page 80', '1/4', 50, 13, 2, false, false, false, false, false, false, false, false, false, false, false),
        ('Tyrannosaurus Rex', 'Monster Manual page 80', '8', 3900, 13, 0, false, false, false, false, false, false, false, false, false, false, false),
        ('Displacer Beast', 'Monster Manual page 81', '3', 700, 13, 2, false, false, true, true, true, false, false, true, false, false, false),
        ('Doppleganger', 'Monster Manual page 82', '3', 700, 14, 4, true, true, true, true, true, true, true, true, false, false, true),
        ('Adult Blue Dracolich', 'Monster Manual page 84', '17', 18000, 19, 0, false, false, false, false, false, false, false, false, false, false, false),
        ('Young Red Shadow Dragon', 'Monster Manual page 85', '13', 10000, 18, 0, false, false, false, false, false, false, false, false, false, false, false),
        ('Ancient Black Dragon', 'Monster Manual page 87', '21', 33000, 22, 2, false, false, false, false, false, false, false, true, false, false, false),
        ('Adult Black Dragon', 'Monster Manual page 88', '14', 11500, 19, 2, false, false, false, false, false, false, false, true, false, false, false),
        ('Young Black Dragon', 'Monster Manual page 88', '7', 2900, 18, 2, false, false, false, false, false, false, false, true, false, false, false),
        ('Black Dragon Wyrmling', 'Monster Manual page 88', '2', 450, 17, 2, false, false, false, false, false, false, false, true, false, false, false),
        ('Ancient Blue Dragon', 'Monster Manual page 90', '23', 50000, 22, 0, false, false, true, false, false, false, false, false, false, false, false),
        ('Adult Blue Dragon', 'Monster Manual page 91', '16', 15000, 19, 0, false, false, true, false, false, false, false, false, false, false, false),
        ('Young Blue Dragon', 'Monster Manual page 91', '9', 5000, 18, 0, false, false, true, false, false, false, false, false, false, false, false),
        ('Blue Dragon Wrymling', 'Monster Manual page 91', '3', 700, 17, 0, false, false, true, false, false, false, false, false, false, false, false),
        ('Ancient Green Dragon', 'Monster Manual page 93', '22', 41000, 21, 1, false, false, false, true, false, false, false, false, false, false, false),
        ('Adult Green Dragon', 'Monster Manual page 94', '15', 13000, 19, 1, false, false, true, false, false, false, false, false, false, false, false),
        ('Young Green Dragon', 'Monster Manual page 94', '8', 3900, 18, 1, false, false, true, false, false, false, false, false, false, false, false),
        ('Green Dragon Wrymling', 'Monster Manual page 95', '2', 450, 17, 1, false, false, true, false, false, false, false, false, false, false, false),
        ('Ancient Red Dragon', 'Monster Manual page 97', '24', 62000, 22, 0, false, false, false, false, false, true, true, false, false, false, false),
        ('Adult Red Dragon', 'Monster Manual page 98', '17', 18000, 19, 0, false, false, false, false, false, true, true, false, false, false, false),
        ('Young Green Dragon', 'Monster Manual page 98', '10', 5900, 18, 0, false, false, false, false, false, true, true, false, false, false, false),
        ('Red Dragon Wrymling', 'Monster Manual page 98', '4', 1100, 17, 0, false, false, false, false, false, true, true, false, false, false, false),
        ('Ancient White Dragon', 'Monster Manual page 100', '20', 25000, 20, 0, true, false, false, false, false, false, false, true, false, false, false),
        ('Adult White Dragon', 'Monster Manual page 101', '13', 10000, 18, 0, true, false, false, false, false, false, false, true, false, false, false),
        ('Young White Dragon', 'Monster Manual page 101', '6', 2300, 17, 0, true, false, false, false, false, false, false, true, false, false, false),
        ('White Dragon Wrymling', 'Monster Manual page 102', '2', 450, 16, 0, true, false, false, false, false, false, false, true, false, false, false),
        ('Ancient Brass Dragon', 'Monster Manual page 104', '20', 25000, 20, 0, false, false, true, false, false, false, false, false, false, false, false),
        ('Adult Brass Dragon', 'Monster Manual page 105', '13', 10000, 18, 0, false, false, true, false, false, false, false, false, false, false, false),
        ('Young Brass Dragon', 'Monster Manual page 105', '6', 2300, 17, 0, false, false, true, false, false, false, false, false, false, false, false),
        ('Brass Dragon Wrymling', 'Monster Manual page 106', '1', 200, 16, 0, false, false, true, false, false, false, false, false, false, false, false),
        ('Ancient Brass Dragon', 'Monster Manual page 107', '22', 41000, 22, 0, false, true, false, false, false, false, false, false, false, false, false),
        ('Adult Bronze Dragon', 'Monster Manual page 108', '15', 13000, 19, 0, false, true, false, false, false, false, false, false, false, false, false),
        ('Young Bronze Dragon', 'Monster Manual page 108', '8', 3900, 18, 0, false, true, false, false, false, false, false, false, false, false, false),
        ('Bonze Dragon Wrymling', 'Monster Manual page 109', '2', 450, 17, 0, false, true, false, false, false, false, false, false, false, false, false),
        ('Ancient Copper Dragon', 'Monster Manual page 110', '21', 33000, 21, 1, false, false, false, false, false, true, false, false, false, false, false),
        ('Adult Copper Dragon', 'Monster Manual page 111', '14', 11500, 18, 1, false, false, false, false, false, true, false, false, false, false, false),
        ('Young Copper Dragon', 'Monster Manual page 111', '7', 2900, 17, 1, false, false, false, false, false, true, false, false, false, false, false),
        ('Copper Dragon Wyrmling', 'Monster Manual page 112', '1', 200, 16, 1, false, false, false, false, false, true, false, false, false, false, false),
        ('Ancient Gold Dragon', 'Monster Manual page 113', '24', 62000, 22, 2, false, true, false, false, true, false, false, false, false, false, false),
        ('Adult Gold Dragon', 'Monster Manual page 114', '17', 18000, 19, 2, false, true, false, false, true, false, false, false, false, false, false),
        ('Young Gold Dragon', 'Monster Manual page 115', '10', 5900, 18, 2, false, true, false, false, true, false, false, false, false, false, false),
        ('gold Dragon Wrymling', 'Monster Manual page 115', '3', 700, 17, 2, false, true, false, false, true, false, false, false, false, false, false),
        ('Ancient Silver Dragon', 'Monster Manual page 116', '23', 30000, 22, 0, false, false, false, false, false, false, true, false, false, false, false),
        ('Adult Silver Dragon', 'Monster Manual page 117', '16', 15000, 19, 0, false, false, false, false, false, false, true, false, false, false, false),
        ('Young Silver Dragon', 'Monster Manual page 118', '9', 5000, 18, 0, false, false, false, false, false, false, true, false, false, false, false),
        ('Silver Dragon Wrymling', 'Monster Manual page 118', '2', 450, 17, 0, false, false, false, false, false, false, true, false, false, false, false),
        ('Dragon Turtle', 'Monster Manual page 119', '17', 18000, 20, 0, false, true, false, false, false, false, false, false, false, true, false),
        ('Drider', 'Monster Manual page 120', '6', 2300, 19, 3, false, false, false, false, false, false, false, false, true, false, false),
        ('Dryad', 'Monster Manaul page 121', '1', 200, 11, 1, false, false, false, true, true, true, false, false, false, false, false),
        ('Duergar', 'Monster Manual page 122', '1', 200, 16, 0, false, false, false, false, false, false, true, false, false, false, true),
        ('Air Elemental', 'Monster Manual page 124', '5', 1800, 15, 5, false, false, false, false, false, false, false, false, false, false, false),
        ('Earth Elemental', 'Monster Manual page 124', '5', 1800, 17, -1, false, false, false, false, false, false, false, false, false, false, false),
        ('Fire Elemental', 'Monster Manual page 125', '5', 1800, 13, 3, false, false, false, false, false, false, false, false, false, false, false),
        ('Water Elemental', 'Monster Manual page 125', '5', 1800, 14, 2, false, false, false, false, false, false, false, false, false, false, false),
        ('Drow', 'Monster Manual page 128', '1/4', 50, 15, 2, false, false, false, false, false, false, false, false, true, false, false),
        ('Drow Elite Warrior', 'Monster Manual page 128', '5', 1800, 18, 4, false, false, false, false, false, false, false, false, true, false, false),
        ('Drow Mage', 'Monster Manual page 129', '7', 2900, 12, 2, false, false, false, false, false, false, false, false, true, false, false),
        ('Drow Priestess of Lolth', 'Monster Manual page 129', '8', 3900, 16, 2, false, false, false, false, false, false, false, false, true, false, false),
        ('Empyrean', 'Monster Manual page 130', '23', 50000, 22, 5, false, false, true, false, false, false, true, false, false, false, false),
        ('Ettercap', 'Monster Manual page 131', '2', 450, 13, 2, false, false, false, true, false, false, false, false, false, false, false),
        ('Ettin', 'Monster Manual page 132', '4', 1100, 12, -1, false, false, false, true, false, false, true, true, false, false, false),
        ('Faerie Dragon (Red, Orange, Yellow)', 'Monster Manual page 133', '1', 200, 15, 5, false, false, false, true, false, false, false, false, false, false, false),
        ('Faerie Dragon (Green, Blue, Indigo, Violet', 'Monster Manual page 133', '2', 450, 15, 5, false, false, false, true, false, false, false, false, false, false, false),
        ('Flame Skull', 'Monster Manual page 134', '4', 1100, 13, 3, false, false, false, false, false, false, false, false, false, false, true),
        ('Flumph', 'Monster Manual page 135', '1/8', 25, 12, 2, false, false, false, false, false, false, false, false, true, false, false),
        ('Fomorian', 'Monster Manual page 136', '8', 3900, 14, 0, false, false, false, false, false, false, false, false, true, false, false),
        ('Gas Spore', 'Monster Manual page 138', '1/2', 100, 5, -5, false, false, false, false, false, false, false, false, true, false, false),
        ('Shrieker', 'Monster Manual page 138', '0', 10, 5, -5, false, false, false, false, false, false, false, false, true, false, false),
        ('Violet Fungus', 'Monster Manual page 138', '1/4', 50, 5, -5, false, false, false, false, false, false, false, false, true, false, false),
        ('Galeb Duhr', 'Monster Manual page 139', '6', 2300, 16, 2, false, false, true, false, false, true, true, false, false, false, false),
        ('Gargolye', 'Monster Manual page 140', '2', 450, 15, 0, false, false, false, false, false, false, false, false, false, false, true),
        ('Doa', 'Monster Manual page 143', '11', 7200, 18, 1, false, false, false, false, false, false, false, false, false, false, false), 
        ('Djinni', 'Monster Manual page 144', '11', 7200, 17, 2, false, false, false, false, false, false, false, false, false, false, false), 
        ('Efreeti', 'Monster Manual page 145', '11', 7200, 17, 1, false, false, false, false, false, false, false, false, false, false, false),
        ('Marid', 'Monster Manual page 146', '11', 7200, 17, 1, false, false, false, false, false, false, false, false, false, false, false),
        ('Ghost', 'Monster Manual page 147', '4', 1100, 11, 1, true, true, true, true, true, true, true, true, true, true, true),
        ('Ghast', 'Monster Manual page 148', '2', 450, 13, 3, true, true, true, true, true, true, true, true, true, false, true),
        ('Ghoul', 'Monster Manual page 148', '1', 200, 12, 2, true, true, true, true, true, true, true, true, true, false, true),
        ('Cloud Giant', 'Monster Manual page 154', '9', 5000, 14, 0, false, false, false, false, false, false, true, false, false, false, false),
        ('Fire Giant', 'Monster Manual page 154', '9', 5000, 18, -1, false, false, false, false, false, false, true, false, false, false, false),
        ('Frost Giant', 'Monster Manual page 155', '8', 3900, 15, -1, true, false, false, false, false, false, true, false, false, false, false),
        ('Hill Giant', 'Monster Manual page 155', '5', 1800, 13, -1, false, false, false, false, false, true, true, false, false, false, false),
        ('Stone Giant', 'Monster Manual page 156', '7', 2900, 17, 2, false, false, false, false, false, false, true, false, true, false, false),
        ('Storm Giant', 'Monster Manual page 156', '13', 10000, 16, 2, false, false, false, false, false, false, true, false, false, false, false),
        ('Gibbering Mouther', 'Monster Manual page 157', '2', 450, 9, -1, false, false, false, false, false, false, false, false, true, false, false),
        ('Githyanki Warrior', 'Monster Manual page 160', '3', 700, 17, 2, false, false, false, false, false, false, false, false, true, false, false),
        ('Githyanki Knight', 'Monster Manual page 160', '8', 3900, 18, 2, false, false, false, false, false, false, false, false, true, false, false),
        ('Githzerai Monk', 'Monster Manual page 161', '2', 450, 14, 2, false, false, false, false, false, false, false, false, true, false, false),
        ('Gtihzerai Zerth', 'Monster Manual page 161', '6', 2900, 17, 4, false, false, false, false, false, false, false, false, true, false, false),
        ('Gnoll', 'Monster Manual page 163', '1/2', 100, 15, 1, false, false, true, true, true, true, false, true, false, false, false),
        ('Gnoll Pack Lord', 'Monster Manual page 163', '2', 450, 15, 2, false, false, true, true, true, true, false, true, false, false, false),
        ('Gnoll Fang of Yeenoghu', 'Monster Manual page 163', '4', 1100, 14, 2, false, false, true, true, true, true, false, true, false, false, false),
        ('Deep Gnome', 'Monster Manual page 164', '1/2', 100, 15, 2, false, false, false, false, false, false, false, false, true, false, false),
        ('Goblin', 'Monster Manual page 166', '1/4', 50, 15, 2, false, true, true, true, true, true, true, true, false, false, false),
        ('Goblin Boss', 'Monster Manual page 166', '1', 200, 17, 2, false, true, true, true, true, true, true, true, false, false, false),
        ('Clay Golem', 'Monster Manual page 168', '9', 5000, 14, -1, false, false, true, false, false, false, false, true, false, false, true),
        ('Flesh Golem', 'Monster Manual page 169', '5', 1800, 9, -1, false, false, false, false, false, false, false, false, false, false, true),
        ('Iron Golem', 'Monster Manual page 170', '16', 15000, 20, -1, false, false, false, false, false, false, false, false, false, false, true),
        ('Stone Golem', 'Monster Manual page 170', '10', 5900, 17, -1, false, false, true, true, false, false, true, false, false, false, true),
        ('Gorgon', 'Monster Manaul page 171', '5', 1800, 19, 0, false, false, false, false, true, false, false, false, false, false, false),
        ('Grell', 'Monster Manual page 172', '3', 700, 12, 2, false, false, false, false, false, false, false, false, true, false, false),
        ('Grick', 'Monster Manual page 173', '2', 450, 14, 2, false, false, false, false, false, false, true, false, true, false, false),
        ('Grick Alpha', 'Monster Manual page 173', '7', 2900, 18, 3, false, false, false, false, false, false, true, false, true, false, false),
        ('Griffin', 'Monster Manual page 174', '2', 450, 12, 2, false, false, false, false, false, false, true, false, false, false, false),
        ('Grimlock', 'Monster Manual page 175', '1/4', 50, 11, 1, false, false, false, false, false, false, false, false, true, false, false),
        ('Half-Red Dragon Veteran', 'Monster Manual page 180', '5', 1800, 18, 1, true, true, true, true, true, true, true, true, false, false, true),
        ('Harpy', 'Monster Manual page 181', '1', 200, 11, 1, false, true, true, false, false, false, true, false, false, false, false),
        ('Hell Hound', 'Monster Manual page 182', '3', 700, 15, 1, false, false, false, false, false, false, false, false, false, false, false),
        ('Helmed Horror', 'Monster Manual page 183', '4', 1100, 20, 1, false, false, false, false, false, false, false, false, false, false, true),
        ('Hippogriff', 'Monster Manual page 184', '1', 200, 11, 1, false, false, false, false, false, false, true, false, false, false, false),
        ('Hobgoblin', 'Monster Manual page 186', '1/2', 100, 18, 1, false, true, true, true, true, true, true, true, false, false, false),
        ('Hobgoblin Captain', 'Monster Manual page 186', '3', 700, 17, 2, false, true, true, true, true, true, true, true, false, false, false),
        ('Hobgoblin Warlord', 'Monster Manual page 187', '6', 2300, 20, 2, false, true, true, true, true, true, true, true, false, false, false),
        ('Homunculus', 'Monster Manual page 188', '0', 10, 13, 2, true, true, true, true, true, true, true, true, false, false, true),
        ('Hooked Horror', 'Monster Manual page 189', '3', 700, 15, 0, false, false, false, false, false, false, false, false, true, false, false),
        ('Hydra', 'Monster Manual page 190', '8', 3900, 13, 1, false, true, false, true, false, false, false, true, false, false, false),
        ('Intellect Devourer', 'Monster Manual page 191', '2', 450, 12, 2, false, false, false, false, false, false, false, false, true, false, false),
        ('Invisible Stalker', 'Monster Manual page 192', '6', 2300, 14, 4, false, false, false, false, false, false, false, false, false, false, false),
        ('Jackalwere', 'Monster Manual page 193', '1/2', 100, 12, 2, false, false, true, false, false, false, false, false, false, false, false),
        ('Kenku', 'Monster Manual page 194', '1/4', 50, 13, 3, false, false, false, true, false, false, false, false, false, false, true),
        ('Winged Kobold', 'Monster Manual page 195', '1/4', 50, 13, 3, false, false, true, false, false, false, true, false, false, false, false),
        ('Kobold', 'Monster Manual page 195', '1/8', 25, 12, 2, false, false, true, false, false, false, true, false, false, false, false),
        ('Kraken', 'Monster Manual page 197', '23', 50000, 18, 0, false, true, false, false, false, false, false, false, false, false, true),
        ('Kuo-Toa', 'Monster Manual page 199', '1/4', 50, 13, 0, false, true, false, false, false, false, false, false, false, true, false),
        ('Kuo-Toa Archpriest', 'Monster Manual page 200', '6', 2300, 13, 2, false, true, false, false, false, false, false, false, false, true, false),
        ('Kuo-Toa Whip', 'Monster Manual page 200', '1', 200, 11, 0, false, true, false, false, false, false, false, false, false, true, false),
        ('Lamia', 'Monster Manual page 201', '4', 1100, 13, 1, false, false, true, false, false, false, false, false, false, false, false),
        ('Lich', 'Monster Manual page 202', '21', 33000, 17, 3, false, false, false, false, false, false, false, false, false, false, false),
        ('Lizardfolk', 'Monster Manual page 204', '1/2', 100, 15, 0, false, false, false, true, true, false, false, false, false, false, false),
        ('Lizardfolk Shaman', 'Monster Manual page 205', '2', 450, 13, 0, false, false, false, true, true, false, false, false, false, false, false),
        ('Lizard King/Queen', 'Monster Manual page 205', '4', 1100, 15, 1, false, false, false, true, true, false, false, false, false, false, false),
        ('Werebear', 'Monster Manual page 208', '5', 1800, 11, 0, false, false, false, true, false, false, false, true, false, false, false),
        ('Wereboar', 'Monster Manual page 209', '4', 1100, 11, 0, false, false, false, true, false, false, false, true, false, false, false),
        ('Wererat', 'Monster Manual page 209', '2', 450, 12, 2, false, false, false, true, false, false, false, true, false, false, true),
        ('Weretiger', 'Monster Manual page 210', '4', 1100, 12, 2, false, true, true, true, true, true, true, true, false, false, false),
        ('Werewolf', 'Monster Manual page 211', '3', 700, 12, 1, false, false, false, true, true, true, true, true, false, false, true),
        ('Magmin', 'Monster Manual page 212', '1/2', 100, 14, 2, false, false, false, false, false, false, false, false, false, false, false),
        ('Manticore', 'Monster Manual page 213', '3', 700, 14, 3, false, false, true, false, false, true, false, false, false, false, false),
        ('Medusa', 'Monster Manual page 214', '6', 2300, 15, 2, false, false, true, false, false, false, false, false, false, false, true),
        ('Dust Mephit', 'Monster Manual page 215', '1/2', 100, 12, 2, false, false, true, false, false, false, false, false, false, false, false),
        ('Ice Mephit', 'Monster Manual page 215', '1/2', 100, 11, 1, true, false, false, false, false, false, false, false, false, false, false),
        ('Magma Mephit', 'Monster Manual page 216', '1/2', 100, 11, 1, false, false, false, false, false, false, true, false, false, false, false),
        ('Mug Mephit', 'Monster Manual page 216', '1/4', 50, 11, 1, false, false, false, false, false, false, false, true, false, false, false),
        ('Smoke Mephit', 'Monster Manual page 217', '1/4', 50, 12, 2, false, false, false, false, false, false, false, false, false, false, true),
        ('Steam Mephit', 'Monster Manual page 217', '1/4', 50, 10, 0, false, true, false, false, false, false, false, false, false, true, true),
        ('Merfolk', 'Monster Manual page 218', '1/8', 25, 11, 1, false, true, false, false, false, false, false, false, false, true, false),
        ('Merrow', 'Monster Manual page 219', '2', 450, 13, 0, false, true, false, false, false, false, false, false, false, true, false),
        ('Mimic', 'Monster Manual page 220', '2', 450, 12, 1, false, false, false, false, false, false, false, false, false, false, true),
        ('Mindflayer', 'Monster Manual page 222', '7', 2900, 15, 1, false, false, false, false, false, false, false, false, true, false, false),
        ('Minotaur', 'Monster Manual page 223', '3', 700, 14, 0, false, true, false, false, true, true, true, false, false, false, false),
        ('Monodrone', 'Monster Manual page 224', '1/8', 25, 15, 1, false, false, false, false, false, false, false, false, false, false, false),
        ('Duodrone', 'Monster Manual page 225', '1/4', 50, 15, 1, false, false, false, false, false, false, false, false, false, false, false),
        ('Tridrone', 'Monster Manual page 225', '1/2', 100, 15, 1, false, false, false, false, false, false, false, false, false, false, false),
        ('Quadrone', 'Monster Manual page 226', '1', 200, 16, 2, false, false, false, false, false, false, false, false, false, false, false),
        ('Pentadrone', 'Monster Manual page 226', '2', 450, 16, 2, false, false, false, false, false, false, false, false, false, false, false),
        ('Mummy', 'Monster Manual page 227', '3', 700, 11, -1, false, false, true, false, false, false, false, true, false, false, true),
        ('Mummy Lord', 'Monster Manual page 229', '15', 13000, 17, 0, false, true, false, false, false, false, false, false, false, false, false),
        ('Myconid Sprout', 'Monster Manual page 230', '0', 10, 10, 0, false, false, false, false, false, false, false, false, true, false, false),
        ('Quaggoth Spore Servant', 'Monster Manual page 230', '1', 200, 13, 1, false, false, false, false, false, false, false, false, true, false, false),
        ('Myconid Adult', 'Monster Manual page 232', '1/2', 100, 12, 0, false, false, false, false, false, false, false, false, true, false, false),
        ('Myconid Sovereign', 'Monster Manual page 232', '2', 450, 13, 0, false, false, false, false, false, false, false, false, true, false, false),
        ('Bone Naga', 'Monster Manual page 233', '4', 1100, 15, 3, false, false, true, true, false, false, false, true, false, false, false),
        ('Spirit Naga', 'Monster Manual page 234', '8', 3900, 15, 3, false, false, true, true, false, false, false, true, false, false, false),
        ('Guardian Naga', 'Monster Manual page 234', '10', 5900, 18, 4, false, false, true, true, false, false, false, true, false, false, false),
        ('Nightmare', 'Monster Manual page 235', '3', 700, 13, 2, false, false, false, false, false, false, false, false, false, false, false),
        ('Nothic', 'Monster Manual page 236', '2', 450, 15, 3, false, false, false, false, false, false, false, false, true, false, true),
        ('Ogre', 'Monster Manual page 237', '2', 450, 11, -1, false, false, false, true, true, true, false, true, false, false, false),
        ('Half Ogre', 'Monster Manual page 238', '1', 200, 12, 0, false, false, false, true, true, true, false, true, false, false, true),
        ('Oni', 'Monster Manual page 239', '7', 2900, 16, 0, false, false, false, false, true, true, true, false, true, false, false),
        ('Black Pudding', 'Monster Manual page 241', '4', 1100, 7, -3, false, false, false, true, false, false, true, true, false, false, true),
        ('Gelatinous Cube', 'Monster Manual page 242', '2', 450, 6, -4, false, false, false, true, false, false, true, true, false, false, true),
        ('Gray Ooze', 'Monster Manual page 243', '1/2', 100, 8, -2, false, false, false, true, false, false, true, true, false, false, true),
        ('Ochre Jelly', 'Monster Manual page 243', '2', 450, 8, -2, false, false, false, true, false, false, true, true, false, false, true),
        ('Orc', 'Monster Manual page 246', '1/2', 100, 13, 1, true, true, true, true, true, true, true, true, false, false, false),
        ('Orc War Chief', 'Monster Manual page 246', '4', 1100, 16, 1, true, true, true, true, true, true, true, true, false, false, false),
        ('Orc Eye of Gruumsh', 'Monster Manual page 247', '2', 450, 16, 1, true, true, true, true, true, true, true, true, false, false, false),
        ('Orog', 'Monster Manual page 247', '2', 450, 18, 1, true, true, true, true, true, true, true, true, false, false, false),
        ('Otyugh', 'Monster Manual page 248', '5', 1800, 14, 0, false, false, false, true, false, false, false, true, false, false, false),
        ('Owlbear', 'Monster Manual page 249', '3', 700, 13, 1, false, false, false, true, false, false, false, true, false, false, false),
        ('Pegasus', 'Monster Manual page 250', '2', 450, 12, 2, false, false, false, false, true, false, true, false, false, false, false),
        ('Peryton', 'Monster Manual page 251', '2', 450, 13, 1, false, false, false, false, false, false, true, false, false, false, false),
        ('Piercer', 'Monster Manual page 252', '1/2', 100, 15, 1, false, false, false, false, false, false, false, false, true, false, false),
        ('Pixie', 'Monster Manual page 253', '1/4', 50, 15, 5, false, false, false, true, false, false, false, false, false, false, false),
        ('Pseodragon', 'Monster Manual page 254', '1/4', 50, 13, 2, false, false, false, true, false, false, false, false, false, false, false),
        ('Purple Worm', 'Monster Manual page 255', '15', 13000, 18, -2, true, true, true, true, true, true, true, true, true, false, false),
        ('Quaggoth', 'Monster Manual page 256', '2', 450, 13, 1, false, false, false, false, false, false, false, false, true, false, false),
        ('Rakshasa', 'Monster Manual page 257', '13', 10000, 16, 3, false, true, true, true, true, true, true, true, false, false, false),
        ('Young Remorhaz', 'Monster Manual page 258', '5', 1800, 14, 1, true, false, false, false, false, false, false, false, false, false, false),
        ('Remorhaz', 'Monster Manual page 258', '11', 7200, 17, 1, true, false, false, false, false, false, false, false, false, false, false),
        ('Revenant', 'Monster Manual page 259', '5', 1800, 13, 2, false, false, false, false, false, false, false, false, false, false, true),
        ('Roc', 'Monster Manual page 260', '11', 7200, 15, 0, false, true, true, false, false, false, true, false, false, false, false),
        ('Roper', 'Monster Manual page 261', '5', 1800, 20, -1, false, false, false, false, false, false, false, false, true, false, false),
        ('Rust Monster', 'Monster Manual page 262', '1/2', 100, 14, 1, false, false, false, false, false, false, true, false, true, false, false),
        ('Sahuagin', 'Monster Manual page 263', '1/2', 100, 12, 0, false, true, false, false, false, false, false, false, false, true, false),
        ('Sahuagin Priestess', 'Monster Manual page 264', '2', 450, 12, 0, false, true, false, false, false, false, false, false, false, true, false),
        ('Sahuagin Baron', 'Monster Manual page 264', '5', 1800, 16, 2, false, true, false, false, false, false, false, false, false, true, false), 
        ('Fire Snake', 'Monster Manual page 265', '1', 200, 14, 2, false, false, true, false, false, false, false, false, false, false, false),
        ('Salamander', 'Monster Manual page 266', '5', 1800, 15, 2, false, false, true, false, false, false, false, false, false, false, false),
        ('Satyr', 'Monster Manual page 267', '1/2', 100, 14, 3, false, true, false, true, true, true, false, false, false, false, false),
        ('Scarecrow', 'Monster Manual page 268', '1', 200, 11, 1, false, false, false, false, true, false, false, false, false, false, false),
        ('Shadow', 'Monster Manual page 269', '1/2', 100, 12, 2, false, false, false, false, false, false, false, false, false, false, true),
        ('Shambling Mound', 'Monster Manual page 270', '5', 1800, 15, -1, false, false, false, true, false, false, false, true, false, false, false),
        ('Shield Guardian', 'Monster Manual page 271', '7', 2900, 17, -1, false, false, false, false, false, false, false, false, false, false, true),
        ('Skeleton', 'Monster Manual page 272', '1/4', 50, 13, 2, true, true, true, true, true, true, true, true, true, true, true),
        ('Minotaur Skeleton', 'Monster Manual page 273', '2', 450, 12, 0, true, true, true, true, true, true, true, true, true, true, true),
        ('Warhorse Skeleton', 'Monster Manual page 273', '1/2', 100, 13, 1, true, true, true, true, true, true, true, true, true, true, true)
